name: Generate Podcast Feeds
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Run Feed Generator
        run: python feed.py
      - name: Push Repo
        run: |
          git config user.name damian
          git config user.email damisoft@gmail.com
          git add .

          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          else
            # proceed with commit or further actions
            git commit -am "Update feeds"
            git push
          fi
